implemented user update and delete
ZHAW-PM4-Compass/compass pull request #90
Opened 2024-05-04 05:14 UTC by noahbaumgartner

This PR closes the issues #13 and #14.

2024-05-04 19:53 UTC, x-snackage-x requested changes
Dieser Merge würde die Test Coverage im BE um ca. 9% verschlechtern. Das ist für mich zu viel. Bitte schreib ein paar Tests für den UserService.

2024-05-04 19:53 UTC, x-snackage-x commented on backend/src/test/resources/application.properties
> +cors.allowedMethods=GET,POST,PUT,PATCH,DELETE
Willst du diese Änderung auch in den main resources auch machen? Weil hier sind die properties von den Tests.

2024-05-06 20:31 UTC, x-snackage-x approved these changes

2024-05-07 05:06 UTC, nob-b3 commented on backend/src/test/resources/application.properties
> +cors.allowedMethods=GET,POST,PUT,PATCH,DELETE
Nein, nehme es gleich wieder raus.

2024-05-07 05:09 UTC, noahbaumgartner commented on backend/src/test/resources/application.properties
> +cors.allowedMethods=GET,POST,PUT,PATCH,DELETE
Ist angepasst

2024-05-07 05:12 UTC, noahbaumgartner commented on backend/src/main/java/ch/zhaw/pm4/compass/backend/service/UserService.java
> +    public String audience;
@Cyrill87 public? Getter und Setter?

2024-05-07 07:48 UTC, merged